// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOMYayEOP10txL41GJD19Elw0rGnkeHI',
    appId: '1:576643122626:web:5125d4152751228f4ac25b',
    messagingSenderId: '576643122626',
    projectId: 'widgetwizards-c50c8',
    authDomain: 'widgetwizards-c50c8.firebaseapp.com',
    storageBucket: 'widgetwizards-c50c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC2bNgx6I34muK1WiqyyMJhD2wzzKkOVk',
    appId: '1:576643122626:android:350f059cca95a6054ac25b',
    messagingSenderId: '576643122626',
    projectId: 'widgetwizards-c50c8',
    storageBucket: 'widgetwizards-c50c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7_dvguPI_c7nxCGldIdd3nzFYFlgmHPI',
    appId: '1:576643122626:ios:851666583b3c06204ac25b',
    messagingSenderId: '576643122626',
    projectId: 'widgetwizards-c50c8',
    storageBucket: 'widgetwizards-c50c8.appspot.com',
    iosBundleId: 'com.example.widgetWizards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7_dvguPI_c7nxCGldIdd3nzFYFlgmHPI',
    appId: '1:576643122626:ios:21180b6e015e01354ac25b',
    messagingSenderId: '576643122626',
    projectId: 'widgetwizards-c50c8',
    storageBucket: 'widgetwizards-c50c8.appspot.com',
    iosBundleId: 'com.example.widgetWizards.RunnerTests',
  );
}
